"""
Gemma4 Shader Build Script
Compiles custom Vulkan GLSL shaders into SPIR-V.
Generates Gemma4.Shaders.rc for Delphi resource embedding.

Usage: python build_shaders.py [--clean]
Run from the shaders/ directory.
"""
import subprocess, sys, os, glob

GLSLC = "glslangValidator.exe"
SRC = "src"
SPV = "spv"
RC_FILE = "Gemma4.Shaders.rc"

# (resource_name, source_file)
SHADERS = [
    ("gemma4_matvec_q4",     "gemma4_matvec_q4.comp"),
    ("gemma4_matvec_f32",    "gemma4_matvec_f32.comp"),
    ("gemma4_rms_norm",      "gemma4_rms_norm.comp"),
    ("gemma4_mul",           "gemma4_mul.comp"),
    ("gemma4_add",           "gemma4_add.comp"),
    ("gemma4_scale",         "gemma4_scale.comp"),
    ("gemma4_gelu",          "gemma4_gelu.comp"),
    ("gemma4_geglu",         "gemma4_geglu.comp"),
    ("gemma4_copy",          "gemma4_copy.comp"),
    ("gemma4_rope",          "gemma4_rope.comp"),
    ("gemma4_rms_norm_rows", "gemma4_rms_norm_rows.comp"),
    ("gemma4_attn_scores",   "gemma4_attn_scores.comp"),
    ("gemma4_softmax_rows",  "gemma4_softmax_rows.comp"),
    ("gemma4_attn_out",      "gemma4_attn_out.comp"),
    ("gemma4_quantize_q8",   "gemma4_quantize_q8.comp"),
    ("gemma4_matvec_q4q8",   "gemma4_matvec_q4q8.comp"),
    ("gemma4_matmat_q4q8",       "gemma4_matmat_q4q8.comp"),
    ("gemma4_rope_batch",        "gemma4_rope_batch.comp"),
    ("gemma4_rope2d",            "gemma4_rope2d.comp"),
    ("gemma4_clamp",             "gemma4_clamp.comp"),
    ("gemma4_kv_append",         "gemma4_kv_append.comp"),
    ("gemma4_attn_scores_batch", "gemma4_attn_scores_batch.comp"),
    ("gemma4_attn_out_batch",    "gemma4_attn_out_batch.comp"),
    ("gemma4_geglu_rows",        "gemma4_geglu_rows.comp"),
    ("gemma4_matmat_f32",        "gemma4_matmat_f32.comp"),
    ("gemma4_attn_scores_bidir", "gemma4_attn_scores_bidir.comp"),
    ("gemma4_attn_out_bidir",    "gemma4_attn_out_bidir.comp"),
    ("gemma4_silu",              "gemma4_silu.comp"),
    ("gemma4_glu",               "gemma4_glu.comp"),
    ("gemma4_dwconv1d",          "gemma4_dwconv1d.comp"),
    ("gemma4_audio_attn",        "gemma4_audio_attn.comp"),
]

def compile_shader(name, src_file):
    src_path = os.path.join(SRC, src_file)
    spv_path = os.path.join(SPV, name + ".spv")

    if not os.path.exists(src_path):
        print(f"  SKIP (not found): {src_file}")
        return False

    args = [GLSLC, "-V", "--target-env", "vulkan1.1", src_path, "-o", spv_path]

    result = subprocess.run(args, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  FAIL: {name}")
        if result.stderr:
            for line in result.stderr.strip().split('\n')[:10]:
                print(f"    {line}")
        return False

    spv_size = os.path.getsize(spv_path)
    print(f"  OK: {name} ({spv_size:,} bytes)")
    return True

def generate_rc(compiled):
    with open(RC_FILE, 'w') as f:
        f.write("// Gemma4 Shader Resources\n")
        f.write("// Auto-generated by build_shaders.py\n\n")
        for name in compiled:
            rc_name = name.upper()
            f.write(f'{rc_name} RCDATA "spv\\{name}.spv"\n')
    print(f"\nGenerated {RC_FILE} with {len(compiled)} entries")

def main():
    os.makedirs(SPV, exist_ok=True)

    if "--clean" in sys.argv:
        for f in glob.glob(os.path.join(SPV, "*.spv")):
            os.remove(f)
        print("Cleaned spv/ directory")

    print(f"Building {len(SHADERS)} shaders...\n")

    compiled = []
    failed = []

    for name, src in SHADERS:
        if compile_shader(name, src):
            compiled.append(name)
        else:
            failed.append(name)

    print(f"\nResults: {len(compiled)} compiled, {len(failed)} failed")

    if failed:
        print(f"\nFailed:")
        for name in failed:
            print(f"  - {name}")

    if compiled:
        generate_rc(compiled)

    return 1 if failed else 0

if __name__ == "__main__":
    sys.exit(main())
